project_id = "avmcintfmjihxxyosecz"

[functions.cloudinary-upload]
verify_jwt = false

[functions.instagram-fetch]
verify_jwt = false

[functions.fetch-brand-logo]
verify_jwt = false

[functions.brand-search]
verify_jwt = false
